version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile_backend
    container_name: backend
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    build:
      context: ..
      dockerfile: infra/Dockerfile_nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
