FROM node:slim AS builder

WORKDIR /app

COPY frontend/ /app/


RUN npm init -y
RUN npm install -D typescript tailwindcss @tailwindcss/cli

COPY frontend/ ./

RUN npx tsc
RUN npx @tailwindcss/cli -i ./input.css -o ./main.css --minify

FROM nginx:stable-alpine

COPY infra/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/index.html /usr/share/nginx/html/
COPY --from=builder /app/main.js /usr/share/nginx/html/
COPY --from=builder /app/main.css /usr/share/nginx/html/