groups:
  - name: BackendAlerts
    rules:
      - alert: BackendDown
        expr: up{job="backend"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Backend server is down"
          description: "No heartbeat from the backend container."

      - alert: HighCPU
        expr: rate(node_cpu_seconds_total{mode="user"}[1m]) > 0.5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "User CPU usage > 50% over last minute."

      - alert: RedisDisconnected
        expr: redis_connected_clients < 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis connection issue"
          description: "No Redis clients connected for 1 minute."

      - alert: ChatSpike
        expr: rate(chat_messages_total[1m]) > 20
        for: 30s
        labels:
          severity: info
        annotations:
          summary: "Chat message spike"
          description: "More than 20 messages/min detected."

