global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'backend_app'
    static_configs:
      - targets: ['backend:3000']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']