global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (métriques système)
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter_prod:9100']

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter_prod:9121']

  # Backend API
  - job_name: 'backend'
    static_configs:
      - targets: ['backend_prod:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx (si tu ajoutes nginx_exporter plus tard)
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx_exporter:9113']

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch_prod:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s 