FROM node:slim

RUN apt-get update && apt-get install -y \
  sqlite3 \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./backend/package*.json ./

RUN npm install

COPY ./backend/ ./
COPY ./backend/.env ./

CMD ["node", "index.js"]