FROM node:slim

RUN apt-get update && apt-get install -y \
  sqlite3 \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Step 1 : Copy only files necessary for dependency install
COPY ./backend/package*.json ./

# Step 2 : Install dependencies
RUN npm install

# Step 3 : Copy the rest of the code (backend)
COPY ./backend/ ./

# Launch the app in watch mode
CMD ["node", "--watch", "--watch-path=.", "index.js"]