FROM node:20-slim

WORKDIR /app

# Installer sqlite3 CLI pour les backups
RUN apt-get update && apt-get install -y sqlite3 && rm -rf /var/lib/apt/lists/*

COPY ./backend/package*.json ./
COPY ./backend/.env ./

RUN npm install

COPY ./backend/ ./

CMD ["node", "index.js"]